---
# 기본 프롬프트 전략 (현재 사용 중인 프롬프트)
name: "default"
description: "기본 리뷰 분석 프롬프트 - JSON 형식 응답"
version: "1.0"

system_prompt: |
  당신은 제품 리뷰 분석 전문가입니다. 
  구매자들의 후회 요인을 분석하여 실용적이고 구체적인 조언을 제공합니다.
  친근하지만 전문적인 톤으로, JSON 형식의 구조화된 분석 결과를 작성합니다.

user_prompt_template: |
  **제품 정보**
  - 카테고리: {category_name}
  - 제품명: {product_name}
  - 분석 대화 턴: {total_turns}턴
  
  {dialogue_section}
  
  **주요 후회 요인 (상위 5개)**
  {factors_list}
  
  **증거 리뷰 전체 ({evidence_count}개)**
  {evidence_reviews}
  
  다음 JSON 형식으로 최종 분석 결과를 작성해주세요:
  {{
    "summary": "핵심 후회 요인 설명 (2-3문장)",
    "key_findings": [
      {{
        "factor": "요인명",
        "risk_level": "high|mid|low",
        "what_users_say": "구매자들이 말하는 내용 (2-3문장)"
      }}
    ],
    "balanced_view": {{
      "pros": [{{"point": "장점"}}],
      "cons": [{{"point": "단점"}}],
      "mixed": [{{"point": "상황에 따라 다름"}}]
    }},
    "decision_rule": {{
      "if_buy": ["구매를 고려해도 좋은 경우"],
      "if_hold": ["보류가 나은 경우"]
    }},
    "final_recommendation": "구매|보류|조건부 추천",
    "one_line_tip": "한 줄 조언"
  }}
  
  **중요**: 반드시 유효한 JSON 형식으로만 응답하세요. 추가 설명이나 마크다운은 포함하지 마세요.

fallback_template: |
  {{
    "summary": "{product_name}의 주요 후회 요인은 {factors_text}입니다.",
    "key_findings": [
      {{
        "factor": "{top_factor}",
        "risk_level": "mid",
        "what_users_say": "구매자들이 이 부분에서 아쉬움을 느끼고 있습니다."
      }}
    ],
    "balanced_view": {{
      "pros": [{{"point": "전반적인 품질은 양호합니다"}}],
      "cons": [{{"point": "{factors_text} 관련 불만이 있습니다"}}],
      "mixed": []
    }},
    "decision_rule": {{
      "if_buy": ["해당 요인이 본인에게 중요하지 않은 경우"],
      "if_hold": ["해당 요인이 본인에게 중요한 경우"]
    }},
    "final_recommendation": "조건부 추천",
    "one_line_tip": "후회 요인을 미리 알고 구매하면 실망을 줄일 수 있습니다!"
  }}
